services:
  db:
    container_name: bot_db_${ENV_TYPE}
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - data_net
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  bot:
    container_name: bot_app_${ENV_TYPE}
    build: .
    restart: unless-stopped
    env_file:
      - ${ENV_FILE}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - data_net
    command: >
      sh -c "
        alembic upgrade head &&
        python main.py
      "
  redis:
    image: redis:7
    container_name: bot_redis_${ENV_TYPE}
    restart: always

volumes:
  pgdata:
    name: pgdata_${ENV_TYPE}

networks:
  data_net:
    name: bot_data_net
