[tool.ruff]
line-length = 120
select = ["E", "F", "N", "I"]
exclude = ["migration"]

[tool.black]
line-length = 120
target-version = ["py312"]

[tool.mypy]
ignore_missing_imports = false

[[tool.mypy.overrides]]
module = "cachetools.*"
ignore_missing_imports = true
